GEN_DATA=None        # Path of the data generated by the trained model
MEM_DATA_STORE=None  # Path where nearest neighbor of generated data and memorization metrics stored
DATA=None           # Training data file
FEATURES_PATH=ffhq_features_300.npy  # Path where script stores training dataset features
                                    # If file exists, uses it instead of computing

python find_dataset_neighbors.py --input_dir=$GEN_DATA --output_dir=$MEM_DATA_STORE \
    --data=$DATA --max_size=5000 --features_path=$FEATURES_PATH --batch=256


